AB#3666 Ingest applications
JupiterOne/graph-microsoft-365 pull request #12
Opened 2021-03-03 15:37 UTC by mknoedel

### What Was Done
- Ingestion of `Detected Application` and `Managed Application`
  entities
- Ingestion of `DeviceHasDetectedApplication`, and
  `DeviceAssignedManagedApplication` relationships
- Updated the Microsoft Graph client to handle individual api calls as well as iterative
  calls.
- Updated the severity of an `unknown` finding from 1 to 4
### Current Type Graph
![image](https://user-images.githubusercontent.com/25489482/109830265-f27daa00-7c03-11eb-99c5-a7c67772b384.png)
### Example Graph
<img width="1171" alt="Screen Shot 2021-03-03 at 8 43 19 AM" src="https://user-images.githubusercontent.com/25489482/109830289-fb6e7b80-7c03-11eb-9060-a26471d16842.png">
<img width="994" alt="Screen Shot 2021-03-03 at 8 43 44 AM" src="https://user-images.githubusercontent.com/25489482/109830309-fe696c00-7c03-11eb-9639-72f7f54ecfd7.png">

2021-03-03 16:32 UTC, mknoedel commented on src/ms-graph/client.ts
> +      for (const value of ensureArray(response.value ?? response)) {
This allows all calls to use `callApi` instead of iterative calls.

2021-03-04 17:45 UTC, austinkelleher requested changes
Looks good! Left a few small comments.

2021-03-04 17:45 UTC, austinkelleher commented on src/steps/intune/steps/applications/converters.ts
> +          managedApp.createdDateTime && +new Date(managedApp.createdDateTime),
Should we use the `parseTimePropertyValue` from `@jupiterone/integration-sdk-core` here?

2021-03-04 17:45 UTC, austinkelleher commented on src/steps/intune/steps/applications/converters.ts
> +          managedApp.createdDateTime && +new Date(managedApp.createdDateTime),
And other timestamp fields

2021-03-04 17:45 UTC, austinkelleher commented on src/steps/intune/steps/applications/converters.ts
> +        isFeatured: managedApp.isFeatured, // Indicates that they are featuring this app on their Company Portal
Wondering if this should just be `featured`? We don't have consistency with our boolean naming

2021-03-04 17:45 UTC, austinkelleher commented on src/utils/ensureArray.ts
> +export function ensureArray<T>(val: T | T[]): T[] {
Thoughts on `toArray`? At first glance, the function sounds like it will return a boolean.

2021-03-04 17:45 UTC, austinkelleher commented on src/steps/intune/steps/applications/index.ts
> +  let detectedAppEntity = detectedApp.id
Super minor...Thoughts on simplifying to:

```typescript
let detectedAppEntity = detectedApp.id && await jobState.findEntity(detectedApp.id);
```

2021-03-04 18:04 UTC, mknoedel commented on src/steps/intune/steps/applications/converters.ts
> +          managedApp.createdDateTime && +new Date(managedApp.createdDateTime),
Sounds good, I'll change to that.

2021-03-04 18:04 UTC, mknoedel commented on src/steps/intune/steps/applications/converters.ts
> +        isFeatured: managedApp.isFeatured, // Indicates that they are featuring this app on their Company Portal
works for me

2021-03-04 18:06 UTC, mknoedel commented on src/steps/intune/steps/applications/index.ts
> +  let detectedAppEntity = detectedApp.id
Sounds good

2021-03-04 18:06 UTC, mknoedel commented on src/utils/ensureArray.ts
> +export function ensureArray<T>(val: T | T[]): T[] {
toArray is fine, I'll change it

2021-03-04 18:10 UTC, mknoedel commented on src/steps/intune/steps/applications/__tests__/__snapshots__/index.test.ts.snap
> +    "
I think it makes the most sense to keep them as is until we have a storage issue. I wouldn't want to remove important information and in the long run there really isn't that much text here. Less than 1 page

2021-03-04 18:58 UTC, aiwilliams submitted a review, later dismissed
Nothing worth undoing the versioning for, but made some comments. Thanks @mknoedel !

2021-03-04 18:58 UTC, aiwilliams commented on CHANGELOG.md
> +  `DeviceAssignedManagedApplication` relationships
I think it would be good to have consistency in our release notes. Check out https://github.com/JupiterOne/graph-google-cloud/blob/master/CHANGELOG.md and https://github.com/JupiterOne/graph-azure/blob/master/CHANGELOG.md. What do you all think about settling on the goal of referencing resources in terms of their `_type` and/or `_class` values (as appropriate) so that customers know what they can begin looking for in queries? I thought these here were `_class` values.

2021-03-04 18:58 UTC, aiwilliams commented on docs/jupiterone.md
> +| `intune_managed_device`       | **HAS**               | `intune_detected_application`  |
Nice choice of relationship classes here!

2021-03-04 18:58 UTC, aiwilliams commented on package.json
> +  "version": "2.0.0",
Why the major version bump? I think we've typically gone with a minor release for new ingestion.

2021-03-04 18:58 UTC, aiwilliams commented on src/steps/intune/steps/deviceConfigurationsAndFindings/utils.ts
> +      return 4;
Is this a bug fix worth noting in CHANGELOG?

2021-03-04 19:02 UTC, mknoedel commented on package.json
> +  "version": "2.0.0",
This release includes changing active directory types from `microsoft_365_` to `azure_` which is a breaking change.

2021-03-04 19:03 UTC, mknoedel commented on src/steps/intune/steps/deviceConfigurationsAndFindings/utils.ts
> +      return 4;
Oops, I added it to the PR comments but not in the changelog. I'll go ahead and add it.

2021-03-04 19:04 UTC, mknoedel commented on CHANGELOG.md
> +  `DeviceAssignedManagedApplication` relationships
Makes sense, I'll update the style.

2021-03-04 19:08 UTC, aiwilliams commented on package.json
> +  "version": "2.0.0",
Ah, gotcha. Perfect. Thanks!

2021-03-04 20:28 UTC, austinkelleher submitted a review, later dismissed

2021-03-04 21:26 UTC, austinkelleher approved these changes

2021-03-04 22:05 UTC, merged

2023-08-08 13:42 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v6.7.0`](https://github.com/JupiterOne/graph-microsoft-365/releases/tag/v6.7.0) :rocket: