AB#4284 & AB#4287 - Get intune account nunber and config status & only ingest Intune data if it is configured
JupiterOne/graph-microsoft-365 pull request #19
Opened 2021-03-15 20:52 UTC by mknoedel

2021-03-15 20:56 UTC, mknoedel commented on src/validateInvocation.ts
> +  await apiClient.verifyAuthentication();
errors are already handled in the `verifyAuthentication` method

2021-03-16 17:07 UTC, aiwilliams commented on src/steps/active-directory/__tests__/index.test.ts
> +describe.skip('fetchAccount', () => {
Please re-request review when these have been re-enabled. Thanks!

2021-03-16 17:07 UTC, aiwilliams commented on src/utils/getStepStartStates.ts
> + */
Thanks for these great comments.

2021-03-17 12:50 UTC, aiwilliams requested changes

2021-03-17 12:50 UTC, aiwilliams commented on src/steps/active-directory/__tests__/converters.test.ts
> +      ],
I think it worthwhile to consider storing the raw data like this:

```suggestion
      _rawData: [
        {
          name: 'default',
          rawData: exampleOrganization,
        },
        {
          name: 'intune',
          rawData: exampleIntuneConfig,
      ],
```

2021-03-17 12:50 UTC, aiwilliams commented on src/steps/active-directory/converters.ts
> +  },
It seems to me that this should be named `intuneConfig` or `intuneSubscription`. The name "extra" isn't very descriptive in other parts of the code, and it seems that it's all Intune related and would probably do well to avoid picking up non-Intune properties in the future.

2021-03-17 12:50 UTC, aiwilliams commented on src/steps/active-directory/__tests__/converters.test.ts
> +      mobileDeviceManagementAuthority: 'mobileDeviceManagementAuthority',
What do you think of:
```suggestion
      intuneMdmAuthority: 'mobileDeviceManagementAuthority',
```

2021-03-17 12:50 UTC, aiwilliams commented on src/steps/intune/steps/devices/__tests__/index.test.ts
> +      DATA_ACCOUT_TYPE,
```suggestion
      DATA_ACCOUNT_ENTITY,
```
I suggest this name because and entity is being stored, not a type. Also fixes typo 😁

2021-03-17 12:50 UTC, aiwilliams commented on src/steps/active-directory/index.ts
> +    );
I think we need to reserve the `logger.error` level for events that warrant investigation. This seems to be designed to log it and carry on, which suggests there is no risk continuing the execution without these details.

Also, I don't think it should be labeled a "dummy" Account when it is an acceptable case that there are no additional details for the Account. Execution should fail when continuation would mean a lot of data is deleted due to an intermittent error in the APIs.

2021-03-17 14:56 UTC, mknoedel commented on src/steps/active-directory/__tests__/converters.test.ts
> +      mobileDeviceManagementAuthority: 'mobileDeviceManagementAuthority',
This doesn't have to be `Intune`. I'll add the options to the left but it can be Office 365 basic MDM, Hybrid on-prem Windows MDM, or Intune

2021-03-17 14:58 UTC, mknoedel commented on src/steps/active-directory/__tests__/converters.test.ts
> +      mobileDeviceManagementAuthority: 'mobileDeviceManagementAuthority',
I think the name makes sense in the context

2021-03-17 15:43 UTC, aiwilliams commented on src/steps/active-directory/__tests__/converters.test.ts
> +      mobileDeviceManagementAuthority: 'mobileDeviceManagementAuthority',
Ahh, I see. Thanks for clarifying!

2021-03-17 18:00 UTC, mknoedel commented on src/steps/active-directory/index.ts
> +    );
Removing this dummy account entity and instead just throw an error.

2021-03-17 21:33 UTC, aiwilliams approved these changes
Thanks for the changes!

2021-03-17 21:33 UTC, aiwilliams commented on CHANGELOG.md
> +  fetching organization data.
Reading the code, it seems that the integration will completely fail to run when we cannot get some details from the AD organization. I think it would be clearer to state that (these become release notes) instead of mentioning a dummy entity that will no longer be created. Also, perhaps we should indicate the message that will be shown to the user?

2021-03-17 21:37 UTC, mknoedel commented on CHANGELOG.md
> +  fetching organization data.
Sounds good, I'll add that to the next pr https://github.com/JupiterOne/graph-microsoft-365/pull/21/files

2021-03-17 21:37 UTC, merged